Don't update doc frame immediately if it is visible, use idle timer
galeo/corfu-doc pull request #6
Opened 2022-02-07 20:21 UTC by AkibAzmain

Updating doc frame immediately makes Emacs slow, specially when browsing the completions.  I changed `corfu-doc--set-timer` to hide doc frame when visible, then update using a **idle** timer instead of a ordinary timer.

2022-02-08 12:02 UTC, galeo requested changes

2022-02-08 12:02 UTC, galeo commented on corfu-doc.el
>             nil #'corfu-doc-show))))
The local set `corfu-doc--candidate` and other local variables may not be updated. Please check `corfu-doc-show`.

2022-02-08 12:02 UTC, galeo commented on corfu-doc.el
>      (setq corfu-doc--timer
This code can be moved to the front.

2022-02-08 12:02 UTC, galeo commented
> Updating doc frame immediately makes Emacs slow, specially when browsing completion candidates.

Indeed in some cases. I have been thinking about whether the code can be adjusted to update the UI asynchronously. No progress. I tried vscode's Intellisense, which was very smooth. I hope the same effect can be achieved someday.

> I changed `corfu-doc--set-timer` to hide doc frame when visible, then update using a **idle** timer instead of a ordinary timer.

Using idle timer may lead to some problem when using with flyspell. Please also see the comments in code review.

You can currently toggle on or off the documentation popup manually. Let's wait for a while to see if there are other ways to improve it. Thanks.

2022-02-09 15:03 UTC, AkibAzmain commented on corfu-doc.el
>             nil #'corfu-doc-show))))
Do you mean that the doc frame might disappear even when the current candidate hasn't changed?  I've already faced that problem while scrolling the doc buffer, so I added a check so that the doc frame disappears only when the current candidate has change (i.e. when `(eq (and (> corfu--total 0) (nth corfu--index corfu--candidates)) corfu-doc--candidate))` evaluates to nil).

2022-02-09 15:06 UTC, AkibAzmain commented on corfu-doc.el
>      (setq corfu-doc--timer
Change to this?

```emacs-lisp
(defun corfu-doc--set-timer (&rest _args)
  (when (and (frame-live-p corfu-doc--frame)
             (frame-visible-p corfu-doc--frame)
             (not (eq (and (> corfu--total 0)
                           (nth corfu--index corfu--candidates))
                      corfu-doc--candidate)))
    (make-frame-invisible corfu-doc--frame))
  (when (or (null corfu-doc--timer)
            (eq this-command #'corfu-doc-manually))
    (setq corfu-doc--timer
          (run-with-idle-timer
           corfu-doc-delay
           nil #'corfu-doc-show))))
```

2022-02-09 16:20 UTC, galeo commented on corfu-doc.el
>             nil #'corfu-doc-show))))
> Do you mean that the doc frame might disappear even when the current candidate hasn't changed?

When select back to a candidate, the `corfu-doc--candidate` may as the same with current candidate. In this case can the doc frame be displayed?

2022-02-11 08:07 UTC, AkibAzmain commented on corfu-doc.el
>             nil #'corfu-doc-show))))
Do you mean this?

```emacs-lisp
(when (frame-live-p corfu-doc--frame)
  (if (not (eq (and (> corfu--total 0)
                    (nth corfu--index corfu--candidates))
               corfu-doc--candidate))
      (when (frame-visible-p corfu-doc--frame)
        (make-frame-invisible corfu-doc--frame))
    (unless (or (frame-visible-p corfu-doc--frame)
                ;; HACK: Make sure the buffer exists and contains
                ;; something
                (and (buffer-live-p (get-buffer " *corfu-doc*"))
                     (zerop (buffer-size (get-buffer " *corfu-doc*"))))
      (make-frame-visible corfu-doc--frame))))
```

2022-02-11 10:20 UTC, galeo commented on corfu-doc.el
>             nil #'corfu-doc-show))))
We may need another local variable to record the candidate for the doc buffer. I'll have a look later.

2022-02-11 12:47 UTC, AkibAzmain commented on corfu-doc.el
>             nil #'corfu-doc-show))))
> We may need another local variable to record the candidate for the doc buffer. I'll have a look later.

Then what's the purpose of `corfu-doc--candidate`?

2022-02-11 13:04 UTC, AkibAzmain commented on corfu-doc.el
>             nil #'corfu-doc-show))))
We won't need the following ugly hack if `corfu-doc--hide` sets `corfu-doc--candidate` to nil (keeping the doc buffer untouched isn't an option, as the doc buffer is global):

```emacs-lisp
;; HACK: Make sure the buffer exists and contains
;; something
(and (buffer-live-p (get-buffer " *corfu-doc*"))
     (zerop (buffer-size (get-buffer " *corfu-doc*"))))
```

2022-02-11 15:23 UTC, closed without merging

2022-02-11 15:29 UTC, galeo commented on corfu-doc.el
>             nil #'corfu-doc-show))))
Yes. There is no need to use another variable to record the candidate for the doc buffer.

2022-02-11 15:45 UTC, galeo commented
Hi @AkibAzmain 

I've been busy recently. I just committed the code to try to solve the problem that this pull request wants to solve. Thanks for your patience to this pull request. Please try it to see if it works well.